config/routes.rb
Rails.application.routes.draw do
  #resources :courses
  get "/courses", to: "courses#index", as: "courses"
  get "/courses/new", to: "courses#new", as: "new_course"
  post "/courses", to: "courses#create"
  get "/courses/:id", to: "courses#show", as: "course"
  get "/courses/:id/edit", to: "courses#edit", as:"edit_course"
  patch "/courses/:id", to: "courses#update"
  delete "/courses/:id", to: "courses#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        @courses = Course.all
    end

    def show
        @course = Course.find(params[:id])
    end

    def new
        @course = Course.new
    end

    def course_params
        params.require(:course).permit(:name, :seat_limit, :classroom_number)
    end

    def create
        @course = Course.create(course_params)
        redirect_to "/courses/#{@course.id}"
    end

    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to courses_path(@course)
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        redirect_to courses_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<h1> Edit Course </h1>

<%= form_for @course do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :seat_limit %>
    <%= f.number_field :seat_limit %>
    <%= f.label :classroom_number %>
    <%= f.number_field :classroom_number %>
    <%= f.submit %>
<% end %>

app/views/courses/index.html.erb
<h1> All the Courses </h1>
<ol>
    <% @courses.each do |course| %>
        
        <li> <%= link_to course.name, course_path(course) %> </li>
    <% end %>
</ol> 

<p> <%= link_to "Create New Course", "/courses/new" %> </p>

app/views/courses/new.html.erb
<h1> Create a new Course! </h1>

<%= form_for(@course) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :seat_limit %>
    <%= f.number_field :seat_limit %>
    <%= f.label :classroom_number %>
    <%= f.number_field :classroom_number %>
    <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h1> Course Information </h1>

<p> <%= @course.name %> </p>
<p> <%= @course.seat_limit %> </p>
<p> <%= @course.classroom_number %> </p>

<%= link_to "See All Courses", courses_path %>
<%= link_to "Edit #{@course.name}", edit_course_path(@course) %>
<%= button_to "Delete Course", "/courses/#{@course.id}", method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PPCourses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>